// Auto-generated by Hydra — DO NOT EDIT MANUALLY
export const deployments: Record<string, any> = {
  "arcTestnet": {
  "network": "arcTestnet",
  "timestamp": "2026-05-17T12:06:59.509Z",
  "deployer": "0x3D261308AE3004e5616b4DA7750daaf458E7Aa23",
  "contracts": {
    "factory": "0xce1f7cd0E7885C7476eC8f6e1Fe345b361813E59",
    "router": "0xd6b3736DA1E07eF4c71Ea9efe4689C83694311e8",
    "pair": "0x992138ef88B4e1a813bE77443A6e1C0d641D34f1",
    "faucet": "0x5ab46777344D460612d927e91a5A136FEC5531DC",
    "pointsTracker": "0x97c18678914B627aEaA9920e85e2E8f6B4CA5F74",
    "oracle": "0xbfF9D5bECE80f29E1aA3A815d024A1605DC6A6E2",
    "yieldFarm": "0x919950A63f469aFa4B790fE994BB346dd72C3D00",
    "staking": "0xeA96df76FF87F8424CEc1defD990E9406a5a44C7"
  },
  "tokens": [
    {
      "symbol": "ATK",
      "address": "0xd80f91409084BF801dfdf82700F0E4a2f07d7D4F"
    },
    {
      "symbol": "ATC",
      "address": "0x256B1C44050BEC3969c813F8bD3DA709F9e43322"
    },
    {
      "symbol": "USDC",
      "address": "0x40D5668e32E8AB1166Fb8CcBF528dc1AF5A8A704"
    }
  ]
}
};

export const defaultNetwork = "arcTestnet";

export const getDeployment = (networkName: string = defaultNetwork) =>
  deployments[networkName] || null;

export const getContractAddress = (
  contractName: string,
  networkName: string = defaultNetwork
) => getDeployment(networkName)?.contracts?.[contractName] || null;
